### ISSUE TITLE
Error: Cannot find method 'onSurfaceSizeChanged' implementation

### ISSUE THREAD

**Issue by adonus19** [NathanaelA/nativescript-exoplayer#43]
When running on Android v27, I see this error. 

I'm using NativeScript v6 with project created from CLI with Angular.

Implementation:
`
import { registerElement } from "nativescript-angular/element-registry";
registerElement('exoplayer', () => require('nativescript-exoplayer').Video);
`

HTML: 
`<exoplayer src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" autoplay="true" height="300">
    </exoplayer>`

StackTrace:
`StackTrace:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     at com.tns.gen.com.google.android.exoplayer2.SimpleExoPlayer_VideoListener.onSurfaceSizeChanged(Unknown Source:21)
System.err:     at com.google.android.exoplayer2.SimpleExoPlayer.maybeNotifySurfaceSizeChanged(SimpleExoPlayer.java:1169)
System.err:     at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurface(SimpleExoPlayer.java:321)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     at com.tns.gen.android.view.TextureView_SurfaceTextureListener.onSurfaceTextureAvailable(TextureView_SurfaceTextureListener.java:22)
System.err:     at android.view.TextureView.getHardwareLayer(TextureView.java:390)
System.err:     at android.view.TextureView.draw(TextureView.java:339)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:19315)
System.err:     at android.view.View.draw(View.java:20093)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:19306)
System.err:     at android.view.View.draw(View.java:20093)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:19306)
System.err:     at android.view.View.draw(View.java:20093)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
System.err:     at android.view.View.draw(View.java:20373)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:19315)
System.err:     at android.view.View.draw(View.java:20093)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
System.err:     at android.view.View.draw(View.java:20373)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:19315)
System.err:     at android.view.View.draw(View.java:20093)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:19306)
System.err:     at android.view.View.draw(View.java:20093)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:19306)
System.err:     at android.view.View.draw(View.java:20093)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:19306)
System.err:     at android.view.View.draw(View.java:20093)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:19306)
System.err:     at android.view.View.draw(View.java:20093)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:19306)
System.err:     at android.view.View.draw(View.java:20093)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:19306)
System.err:     at android.view.View.draw(View.java:20093)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
System.err:     at android.view.View.draw(View.java:20373)
System.err:     at com.android.internal.policy.DecorView.draw(DecorView.java:980)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:19315)
System.err:     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
System.err:     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
System.err:     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
System.err:     at android.view.ViewRootImpl.draw(ViewRootImpl.java:3496)
System.err:     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3283)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2818)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:723)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:658)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
System.err:     at android.os.Handler.handleCallback(Handler.java:789)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6944)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by ninjaonsafari** [comment]
i'm getting the same error...

```
"nativescript-angular": "^8.2.0",
"nativescript-exoplayer": "^4.0.1",
```

**Comment by abozanona** [comment]
+1

**Comment by mirkospagnol** [comment]
+1

**Comment by lecaobaophuc0912** [comment]
This is issue only get in nativescript-exoplayer 4.0.2. Let remove "^" into  "^4.0.1" in package json, remove platform, node_modules and retry.
```
"nativescript-angular": "^8.2.0",
"nativescript-exoplayer": "4.0.1",
```
